### ISSUE TITLE
Need Ros2 node to connect zed and Nvidia Isaac packages

### ISSUE THREAD

**Issue by Supernova1114** [SC-Robotics-2023/autonomy_2022_23#3]
Need to create Ros2 node that can take output images and imu info from zed, and send the info to topics in the isaac packages.

https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_proximity_segmentation
https://github.com/stereolabs/zed-ros2-wrapper

Isaac VSLAM Topics
- https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#ros-topics-subscribed
  - Will need all subscribed (input) topics:
  - /stereo_camera/left/image
  - /stereo_camera/left/camera_info
  - /stereo_camera/right/image
  - /stereo_camera/right/camera_info
  - visual_slam/imu
- https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam#ros-topics-published
- For published (output) topics, only need info from 
  - visual_slam/tracking/slam_path
  - visual_slam/tracking/vo_path
  - visual_slam/status
- Click on the "interface" links on the isaac vslam repo page to get info on data type transfer for each topic.

Zed output topics:
- I need to get the zed wrapper running again to see the topic names. (TODO)

Isaac proximity segmentation:
- I have yet to test package (TODO)

**Comment by Supernova1114** [comment]
There should be enough info to get started. I need to finish some info on zed and proximity segmentation.

**Comment by austinlake04** [comment]
Thanks Cameron, this is great. Next time we are both in the lab I can give you a run down of what the _middleman_ node would look like and how it functions. I'll work on this and try to get something for you to test in the next few of days.

**Comment by Supernova1114** [comment]
Update:
- Isaac VSLAM will not work for Nav2, will be using another method for VSLAM.
